// Next.js API route support: https://nextjs.org/docs/api-routes/introduction
import type { NextApiRequest, NextApiResponse } from "next";

type Data = {
    name: string;
};

export default function handler(req: NextApiRequest, res: NextApiResponse) {
    res.status(200).json({
        t01d: "https://raw.githubusercontent.com/basmilius/weather-icons/dev/production/fill/svg/thunderstorms-day-rain.svg",
        t01n: "url",
        t02d: "url",
        t02n: "url",
        t03d: "url",
        t03n: "url",
        t04d: "url",
        t04n: "url",
        t05d: "url",
        t05n: "url",
        d01d: "url",
        d01n: "url",
        d02d: "url",
        d02n: "url",
        d03d: "url",
        d03n: "url",
        r01d: "url",
        r01n: "url",
        r02d: "url",
        r02n: "url",
        r03d: "url",
        r03n: "url",
        f01d: "url",
        f01n: "url",
        r04d: "url",
        r04n: "url",
        r05d: "url",
        r05n: "url",
        r06d: "url",
        r06b: "url",
        s01d: "url",
        s01n: "url",
        s02d: "url",
        s02n: "url",
        s03d: "url",
        s03n: "url",
        s04d: "url",
        s04n: "url",
        s05d: "url",
        s05n: "url",
        s06d: "url",
        s06n: "url",
        a01d: "url",
        a01n: "url",
        a02d: "url",
        a02n: "url",
        a03d: "url",
        a03n: "url",
        a04d: "url",
        a04n: "url",
        a05d: "url",
        a05n: "url",
        a06d: "url",
        a06n: "url",
        c01d: "url",
        c01n: "url",
        c02d: "url",
        c02n: "url",
        c03d: "url",
        c03n: "url",
        c04d: "url",
        c04n: "url",
        u00d: "url",
        u00n: "url"
    });
}
